### ISSUE TITLE
File extension search doesn't work

### ISSUE THREAD

**Issue by ghost** [TheRealVira/FileSearch#1]
Plz fix

**Comment by TheRealVira** [comment]
Dear butchcom. Plaese be more specific with your needs! :v:

**Comment by ghost** [comment]
Simply put, if I click on the 'Search' button, the search yields no result (I have specified a directory and a file extension).

**Comment by TheRealVira** [comment]
What options did you take in the "drop downs"?

**Comment by TheRealVira** [comment]
Well I think I see from where you're comming from. Simple fix -> Build in "Release" mode.

You may ask why. Thats a simple one. I've created the "TestingPurpose" attribute, which allows us to create algorithms which aren't working yet and which only show up in "Debug" mode.

It's not a bug. It's a feature! :grin:

**Comment by ghost** [comment]
Please add that information to the readme

**Comment by TheRealVira** [comment]
All done and dusted.
